### ISSUE TITLE
New fonts

### ISSUE THREAD

**Issue by gwolf2u** [crdroidandroid/android_packages_apps_crDroidFonts#1]
@neobuddy89 
Request from a user of mine, to add new fonts 
Link below
https://drive.google.com/file/d/1lnQP3TbtlhILya4YMcojXrYVtRLpgFD3/view

**Comment by neobuddy89** [comment]
Can you add and test this?

**Comment by gwolf2u** [comment]
move to pending for now
testing later

**Comment by neobuddy89** [comment]
Not sure on xml generation...

**Comment by gwolf2u** [comment]
Yeah reason for moving to pending
I need a weekend to test
