### ISSUE TITLE
Issues with some added new features

### ISSUE THREAD

**Issue by SMARTSKA97** [crdroidandroid/android_packages_apps_crDroidFonts#2]
smartpixels, call recording is not working, ambient display is not working....
i dont know how to reproduce the errors...
hope devs please look into this...

**Comment by neobuddy89** [comment]
This is not right place. Please post in your respective device forum.

**Comment by gwolf2u** [comment]
@SMARTSKA97 contact your maintainer 
feature is working properly on most devices
